price_pool_ttl: 10
aggregator_nodes: 3
consensus_threshold: 0.01
aggr_dev_perc: 0.2
SERVER_PORT: 8000
RELAY_TIME_THRESHOLD: 10 # minutes
assets:
  - name: "USDT/USD"
    internalAssetIdentity: "0xUSDT"
    feeds:
      - name: "pyth"
        interval: 10
        assetID: "2b89b9dc8fdf9f34709a5b106b472f0f39bb6ca9ce04b0fd7f2e971688e2e53b"
      - name: "moralis"
        interval: 30
        assetID: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
  - name: "ETH/USD"
    internalAssetIdentity: "0xETH"
    feeds:
      - name: "pyth"
        interval: 5
        assetID: "ff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace"
      - name: "coingecko"
        interval: 276
        assetID: "2b89b9dc8fdf9f34709a5b106b472f0f39bb6ca9ce04b0fd7f2e971688e2e53b"
  - name: "CNGN/USD"
    internalAssetIdentity: "0xCNGN"
    feeds:
      - name: "monierate"
        interval: 50
        assetID: "NGN"
      - name: "exchangerate"
        interval: 62
        assetID: "NGN"
      - name: "twelvedata"
        interval: 64
        assetID: "NGN"
      - name: "currencylayer"
        interval: 66
        assetID: "NGN"
  - name: "BRL/USD"
    internalAssetIdentity: "0xBRL"
    feeds:
      - name: "exchangerate"
        interval: 60
        assetID: "BRL"
      - name: "twelvedata"
        interval: 60
        assetID: "BRL"
      - name: "fixer"
        interval: 60
        assetID: "BRL"
      - name: "currencylayer"
        interval: 60
        assetID: "BRL"
contracts:
  - address: "0xC08CbF336cC0D7163Ef260bF69137c8cA7AF2F3a"
    abi: "0x"
    chainID: "84532"
    chainName: "base-testnet"
    rpc: ""
