// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/assets": {
            "get": {
                "description": "Returns list of all available assets",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "assets"
                ],
                "summary": "Get available assets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/config.AssetConfig"
                            }
                        }
                    }
                }
            }
        },
        "/issuances/{id}": {
            "get": {
                "description": "Returns details of a specific issuance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "issuances"
                ],
                "summary": "Get issuance details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Issuance ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Issuance"
                        }
                    }
                }
            }
        },
        "/prices/last": {
            "get": {
                "description": "Returns the last known price for a specific asset or all assets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prices"
                ],
                "summary": "Get last price for an asset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID to get price for",
                        "name": "asset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "number"
                            }
                        }
                    }
                }
            }
        },
        "/prices/stream": {
            "get": {
                "description": "Server-Sent Events stream of price updates",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "prices"
                ],
                "summary": "Stream price updates",
                "responses": {
                    "200": {
                        "description": "SSE stream",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "config.AssetConfig": {
            "type": "object",
            "properties": {
                "feeds": {
                    "description": "List of feeds",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/config.FeedConfig"
                    }
                },
                "internalAssetIdentity": {
                    "description": "eg \"0xUSDT\"",
                    "type": "string"
                },
                "name": {
                    "description": "e.g., \"BTC/USD\"",
                    "type": "string"
                }
            }
        },
        "config.FeedConfig": {
            "type": "object",
            "properties": {
                "assetID": {
                    "type": "string"
                },
                "interval": {
                    "description": "Seconds (e.g., 5)",
                    "type": "integer"
                },
                "name": {
                    "description": "e.g., \"binance\"",
                    "type": "string"
                }
            }
        },
        "models.Issuance": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "issuance_id": {
                    "type": "string"
                },
                "issuance_state": {
                    "$ref": "#/definitions/models.IssuanceState"
                },
                "issuer_address": {
                    "type": "string"
                },
                "metadata": {},
                "price": {
                    "$ref": "#/definitions/models.UnifiedPrice"
                },
                "price_asset_id": {
                    "type": "string"
                },
                "price_source": {
                    "type": "string"
                },
                "price_timestamp": {
                    "type": "string"
                },
                "price_value": {
                    "description": "Normalized price value with 5 decimal places",
                    "type": "number"
                },
                "round_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.IssuanceState": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "Denied",
                "Approved",
                "Confirmed"
            ]
        },
        "models.UnifiedPrice": {
            "type": "object",
            "properties": {
                "assetID": {
                    "type": "string"
                },
                "expo": {
                    "type": "integer"
                },
                "req_hash": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "value": {
                    "description": "Cant use in64 due to overflow",
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5001",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Oracle Engine API",
	Description:      "API for accessing oracle price data and issuances",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
