basePath: /api
definitions:
  models.AssetData:
    properties:
      asset:
        type: string
      asset_id:
        type: string
    type: object
  models.Issuance:
    properties:
      created_at:
        type: string
      issuance_id:
        type: string
      issuance_state:
        $ref: '#/definitions/models.IssuanceState'
      issuer_address:
        type: string
      metadata: {}
      price:
        $ref: '#/definitions/models.UnifiedPrice'
      price_asset_id:
        type: string
      price_source:
        type: string
      price_timestamp:
        type: string
      price_value:
        description: Normalized price value with 5 decimal places
        type: number
      round_id:
        type: integer
      updated_at:
        type: string
    type: object
  models.IssuanceState:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - Denied
    - Approved
    - Confirmed
  models.Price:
    properties:
      asset:
        type: string
      expo:
        type: integer
      id:
        type: string
      internal_asset_identity:
        type: string
      req_url:
        type: string
      source:
        type: string
      timestamp:
        type: string
      value:
        type: number
    type: object
  models.PriceAudit:
    properties:
      aggregated_price:
        $ref: '#/definitions/models.UnifiedPrice'
      asset_id:
        type: string
      created_at:
        type: string
      price_id:
        type: string
      raw_prices:
        items:
          $ref: '#/definitions/models.Price'
        type: array
      updated_at:
        type: string
    type: object
  models.PriceChange:
    properties:
      change:
        description: Absolute change
        type: number
      change_pct:
        description: Percentage change
        type: number
      from_price:
        description: Starting price
        type: number
      from_time:
        description: Starting time
        type: string
      period:
        description: e.g. "7d", "3d", "24h"
        type: string
      to_price:
        description: Current price
        type: number
      to_time:
        description: Current time
        type: string
    type: object
  models.UnifiedPrice:
    properties:
      assetID:
        type: string
      connected_price_ids:
        items:
          type: string
        type: array
      expo:
        type: integer
      id:
        type: string
      is_aggr:
        description: is aggregated
        type: boolean
      price_changes:
        description: Optional price changes
        items:
          $ref: '#/definitions/models.PriceChange'
        type: array
      req_hash:
        type: string
      req_url:
        description: this is req url but not for aggr price
        type: string
      source:
        type: string
      timestamp:
        type: string
      value:
        description: Cant use in64 due to overflow
        type: number
    type: object
host: 146.190.186.116:8000
info:
  contact:
    email: ifalabstudio@gmail.com
    name: IfaLabs
    url: https://ifalabs.com
  description: IFA LABS Oracle Engine API provides real-time, reliable asset prices
    using an aggregated moving window algorithm to ensure stability and reduce manipulation.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Oracle Engine API
  version: "1.0"
paths:
  /assets:
    get:
      description: Returns list of all available assets
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.AssetData'
            type: array
      summary: Get available assets
      tags:
      - assets
  /issuances/{id}:
    get:
      consumes:
      - application/json
      description: Returns details of a specific issuance
      parameters:
      - description: Issuance ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Issuance'
      summary: Get issuance details
      tags:
      - issuances
  /prices/{id}/audit:
    get:
      consumes:
      - application/json
      description: Returns audit information for a specific price
      parameters:
      - description: Price ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PriceAudit'
      summary: Get price audit
      tags:
      - prices
  /prices/last:
    get:
      consumes:
      - application/json
      description: Returns the last known price for a specific asset or all assets
      parameters:
      - description: Asset ID to get price for
        in: query
        name: asset
        type: string
      - description: Comma-separated list of price change periods (e.g. '7d,3d,24h').
          Default is '7d'
        in: query
        name: changes
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/models.UnifiedPrice'
            type: object
      summary: Get last price for an asset
      tags:
      - prices
  /prices/stream:
    get:
      description: Server-Sent Events stream of price updates, have a retry mechanism
        in place for break
      produces:
      - text/event-stream
      responses:
        "200":
          description: SSE stream
          schema:
            type: string
      summary: Model Stream price updates
      tags:
      - prices
swagger: "2.0"
